site_name: django-upload-to

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
        - bash

nav:
  - django-upload-to: index.md
  - How-To Guides: how-to-guides.md
