name: Release
on:
  release:
    types:
      - created
permissions:
  contents: write
jobs:
  publish:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Build
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.3"
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build
      - name: Publish docs
        run: |
          poetry install
          mkdocs gh-deploy --force
